with open('c:\\Users\\Admin\\Desktop\\CÁC TOOL TÂM ĐẮC\\RUN_VEO_4.0_V2.2.6.exe_extracted\\status_panel.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = lines[:332] + [
    '        except Exception as e:\n',
    '            self.completed.emit({"success": False, "message": str(e)})\n',
    '        finally:\n',
    '            try:\n',
    '                if auto is not None:\n',
    '                    loop.run_until_complete(asyncio.wait_for(auto.close(), timeout=10))\n',
    '            except Exception:\n',
    '                pass\n',
    '            try:\n',
    '                pending = [task for task in asyncio.all_tasks(loop) if not task.done()]\n',
    '                for task in pending:\n',
    '                    task.cancel()\n',
    '                if pending:\n',
    '                    loop.run_until_complete(asyncio.gather(*pending, return_exceptions=True))\n',
    '            except Exception:\n',
    '                pass\n',
    '            try:\n',
    '                loop.run_until_complete(loop.shutdown_asyncgens())\n',
    '            except Exception:\n',
    '                pass\n',
    '            try:\n',
    '                asyncio.set_event_loop(None)\n',
    '            except Exception:\n',
    '                pass\n',
    '            loop.close()\n',
    '\n',
    'import asyncio\n',
    '\n',
    'class _StorytellingExportWorker(QThread):\n',
    '    log_message = pyqtSignal(str)\n',
    '    completed = pyqtSignal(dict)\n',
    '\n',
    '    def __init__(\n',
    '        self,\n',
    '        items: list[dict],\n',
    '        output_dir: str,\n',
    '        voice_key: str,\n',
    '        tts_provider: str,\n',
    '        aspect_ratio: str,\n',
    '        enable_motion: bool = True,\n',
    '        parent: QWidget | None = None,\n',
    '    ):\n',
    '        super().__init__(parent)\n',
    '        self._items = list(items or [])\n',
    '        self._output_dir = str(output_dir or "")\n',
    '        self._voice_key = str(voice_key or "None_NoVoice")\n',
    '        self._tts_provider = str(tts_provider or "auto")\n',
    '        self._aspect_ratio = str(aspect_ratio or "9:16")\n',
    '        self._enable_motion = bool(enable_motion)\n',
    '\n',
    '    def run(self) -> None:\n',
    '        try:\n',
    '            from storytelling_exporter import export_storytelling_video\n',
    '\n',
    '            out_path = export_storytelling_video(\n',
    '                self._items,\n',
    '                self._output_dir,\n',
    '                voice_key=self._voice_key,\n',
    '                tts_provider=self._tts_provider,\n',
    '                aspect_ratio=self._aspect_ratio,\n',
    '                enable_motion=self._enable_motion,\n',
    '                log_callback=self.log_message.emit,\n',
    '            )\n',
    '            self.completed.emit({"success": True, "path": out_path})\n',
    '        except BaseException as exc:\n',
    '            self.completed.emit({"success": False, "message": str(exc)})\n',
    '\n',
    '\n',
    'class StatusPanel(QWidget):\n',
    '    COL_CHECK = 0\n',
    '    COL_STT = 1\n',
    '    COL_VIDEO = 2\n',
    '    COL_STATUS = 3\n',
    '    COL_MODE = 4\n',
    '    COL_PROMPT = 5\n',
    '\n',
    '    MODE_TEXT_TO_VIDEO = "text_to_video"\n',
    '    MODE_IMAGE_TO_VIDEO_SINGLE = "image_to_video_single"\n',
    '    MODE_IMAGE_TO_VIDEO_START_END = "image_to_video_start_end"\n',
    '    MODE_CHARACTER_SYNC = "character_sync"\n',
    '    MODE_CREATE_IMAGE_PROMPT = "create_image_prompt"\n',
    '    MODE_CREATE_IMAGE_REFERENCE = "create_image_reference"\n',
    '    MODE_GROK_TEXT_TO_VIDEO = "grok_text_to_video"\n',
    '    MODE_GROK_IMAGE_TO_VIDEO = "grok_image_to_video"\n',
    '    MODE_COPY_VIDEO = "copy_video"\n',
    '    AUTO_RETRY_ERROR_CODES = {"403", "13", "500"}\n',
    '    AUTO_RETRY_MAX_PER_ROW = 1\n',
    '\n',
    '    requestStop = pyqtSignal()\n',
    '    runStateChanged = pyqtSignal(bool)\n',
    '    titleChanged = pyqtSignal(str)\n'
] + lines[332:]

with open('c:\\Users\\Admin\\Desktop\\CÁC TOOL TÂM ĐẮC\\RUN_VEO_4.0_V2.2.6.exe_extracted\\status_panel.py', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
print('Done!')
